
services:

  git:
    build:  .
    container_name: git
    ports:
      - "${PORT:-8000}:8000"
    security_opt: 
      - label=disable
    volumes:
      - ./:/docs
    stdin_open: true
    tty: true


