site_name: Git


site_description: Resumen sobre Git
site_url: https://alejrot.github.io/git/


repo_url: https://github.com/alejrot/git
repo_name: git
edit_uri: edit/master/docs/

copyright: Copyright &copy; 2024 Marcelo Marot Rosas


theme:
  name: material
  language: es
  font: false   # previene carga de Google Fonts

  icon: 
    # logo: fontawesome/solid/user-nurse
    logo: simple/git  # :simple-git:

    tag:
      git: simple/git 
      github: simple/github 
      bash: simple/gnubash


  palette:
  # Palette toggle for light mode
  # - media: "(prefers-color-scheme)"
  #   toggle:
  #     icon: material/lightbulb-auto
  #     name: Modo automático
      
  # Palette toggle for light mode
  - media: "(prefers-color-scheme: light)"
    scheme: default
    primary: orange
    accent: red 
    toggle:
      icon: material/lightbulb 
      name: Modo claro

  # Palette toggle for dark mode
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: orange
    accent: lime 
    toggle:
      icon: material/lightbulb-outline
      name: modo oscuro

  features:
    # carga instantánea (requiere site_url)
    - navigation.instant
    - navigation.instant.preview
    # indice flotante (a derecha tipicamente)
    - navigation.tabs
    - navigation.instant
    - navigation.instant.progress   # progreso de carga (conexiones lentas)
    - navigation.tracking
    # sugerencias de busqueda y remarcar resultados
    - search.suggest
    - search.highlight
    - search.share    # boton compartir
    # header
    - header.autohide # ocultamiento automatico
    - navigation.footer

    - content.code.copy # copiad bloques de codigo
    - content.code.annotate # anotaciones desplegables en código
    
    - content.tabs.link # pestañas interna solidarias

extra_css:
  - stylesheets/extra.css

plugins:
  - search
  # etiquetas
  - tags:
      tags_file: tags.md


extra:

  tags:
    Git: git
    GitHub: github
    Bash: bash

markdown_extensions:
  - abbr
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  # - pymdownx.snippets
  - pymdownx.snippets:
      auto_append:
        - includes/glosario.md
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - tables
  - pymdownx.tabbed:
      alternate_style: true

  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite   # habilita remarcado de renglones
  - pymdownx.snippets       # habilita importar código de otros archivos
  - pymdownx.superfences    # habilita anidado de otros contenidos

  - footnotes
  
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde

  - attr_list
  - md_in_html

  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

  - abbr
  - attr_list


watch:
  - includes


nav:
  - Indice: index.md
  - Git:
    - Introducción: git/intro.md
    # - Comandos de Bash: git/comandos.md
    - Configuracion inicial: git/configuracion_inicial.md
    - Uso básico: git/uso_basico.md
    - Archivo de excepciones: git/gitignore.md
    - Bifurcaciones: git/bifurcaciones.md
    - Commits previos:  git/commits_previos.md
    - Repositorios remotos: git/repositorio_remoto.md


  - Extras:
    - Comandos Bash: extra/comandos.md
    - Taller Midudev: extra/taller_midu.md
    - Alias y Comandos personalizados: git/alias_comandos.md

  - Borradores:
    - borradores/comandos_bash.md
    - borradores/enlaces.md
    - borradores/forkear.md
    - borradores/gh_pages.md
    - borradores/git.md
    - git/commits_previos.md
    - git/repositorio_remoto.md


#     - Tags: git/tags.md
#     - Alias y Comandos personalizados: git/alias_comandos.md

#     - DESORDENADO : git.md

  
#     - Enlaces y referencias: enlaces.md
  
  
  
#   - GitHub:
#     - GitHub Pages: gh_pages.md

  - Tags: tags.md

